steps:
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-f', 'docker/swan.Dockerfile', '-t', 'us-central1-docker.pkg.dev/oceanum-prod/oceanum-public/swan', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'docker/rompy.Dockerfile', '-t', 'us-central1-docker.pkg.dev/oceanum-prod/oceanum-public/rompy', '.']

images:
  # - us-central1-docker.pkg.dev/oceanum-prod/oceanum-public/swan
  - us-central1-docker.pkg.dev/oceanum-prod/oceanum-public/rompy

